= Back-Mozzarella auf Paprikagemüse

== Zutaten

* 4 Scheiben Bauern- oder Toskanabrot
* 8 EL Olivenöl
* 4 Kugeln Mozzarella (je 125 g)
* 2 Paprikaschoten
* 1 Knoblauchzehe
* 1 Zwiebel
* 1 Biozitrone
* 1 Zweig Rosmarin
* Salz & Pfeffer

== Zubereitung

. Die Brotscheiben mit 2 EL Olivenöl bepinseln oder beträufeln, salzen und auf das Ofengitter legen. 
. Die Mozzarellakugeln trocken tupfen, kreuzförmig einschneiden und in eine ofenfeste Form setzen. 
Zitrone heiß abwaschen, trocken reiben, dünne Scheiben abschneiden und in die Mozzarellakugeln stecken.
. Den Knoblauch schälen. 
Den Rosmarin waschen und trocken schütteln, die Nadeln und den Knoblauch fein hacken. 
Vom Rest der Zitrone die Schale abreiben und den Saft auspressen.
Alles mit 2 EL Olivenöl verrühren und mit Salz und Pfeffer würzen.
Die Soße über den Mozzarella gießen und den Backofen auf 220 °C vorheizen.
. Für das Paprikagemüse die Paprikaschoten waschen, halbieren, entkernen und in Streifen schneiden.
Die Zwiebel schälen und ebenfalls in Streifen schneiden.
. In einer Pfanne 4 EL Olivenöl erhitzen und die Paprika- und Zwiebelstreifen darin ca. 12 Minuten anbraten.
Nach 6 Minuten Bratzeit den Mozzarella in den heißen Ofen (Mitte) schieben, die Brote auf dem Rost direkt darüber. Käse und Brote ca. 5 Minuten rösten.
. Das Paprikagemüse mit Salz und Pfeffer würzen, dann mit Mozzarella und Röstbrot servieren.