= Cheesecake Double Nougat

== Zutaten

* 250 g Butterkekse
* 70 g Butter
* 1 Stange Nougat Noir
* 1 Stange Nougat Krokant
* 600 g Frischkäse
* 200 g Crème fraîche
* 80 g Zucker
* 1 Vanilleschote
* 4 Eier
* Schalte einer Zitrone
* 1 Prise Meersalz

== Zubereitung

. Die Kekse in einem Mixer fein mahlen oder in einem Gefrierbeutel geben und mit einem Nudelholz klein walzen.
. Eine Springform einfetten, den backofen auf 160 °C vorheizen.
. Die Butter mit den Kekskrümeln und einer Prise Salz vermischen und in der gefetteten Form gleichmäßig fest drücken.
Für ca. 25 Minuten kalt stellen.
. Die Nougatsorten in zwei verschiedene Schüsseln auf dem Wasserbad schmelzen.
. Frischkäse, Crème fraîche, Zucker, ZTitronenschalt und Vanillemark verrühren.
Die Eier danach hinzugeben und vorsichtig, ohne Luftblasen zu schlagen, unterrühren.
. Die Hälfte dieser Masse mit dem geschmolzenen Nougat Noir, die andere Hälfte mit Nougat Krokant vermengen.
Zuerst die Krokantmasse vorsichtig auf dem Keksboden verteilen. 
Dann die Noirmasse darauf geben und mit einer Gabel mamorieren.
. Die Springform mit Alufolie einschlagen, um sie abzudichten.
. Ein tiefes Bleck mit Wasser füllen und die Springform in das Wasserbad stellen.
Im Ofen für ca. 1 Stunde backen.
Wichtig: Während der Backzeit den Ofen nicht öffnen!
. Den Cheesecake herausnehmen und für einen Tag kalt stellen.