= Chicken Tikka Masala

== Zutaten

* 400 g Hähnchenbrust
* 250 ml Naturjoghurt
* 30 g Ingwer
* 1 Zwiebel
* 200 g Fleischtomate
* 2 Chilischoten
* 2 Knoblauchzehen
* 2 TL Koriandersamen
* 2 TL Senfkörner
* 2 EL Pflanzenöl
* 1 EL Tomatenmark
* 200 g passierte Tomaten
* 1 Bund Koriander
* 5 EL Limettensaft
* 1 Limettenabrieb
* Salz

== Zubereitung

. Die Hühnerbrust grob würfeln und in einer Schüssel mit dem Joghurt vermengen und abgedeckt für 4-6 Stunden oder über Nacht im Kühlschrank einlegen.
. Den Ingwer und die Zwiebeln schälen und die Tomaten, Zwiebeln und den Ingwer in feine Würfel schneiden.
Die Kerne der Chilischoten entfernen und klein hacken und den Knoblauch in Würfel schneiden.
. Die Koriandersamen, Senfkörner, Chilischote und die Knoblauchzehen in einer Pfanne anrösten.
. Die Gewürzmischung, Tomaten, Zwiebeln, Knoblauch, Ingwer und Chili mit etwas Salz in einen Mörser geben und zhu einer Paste mörsen.
. Die Hühnerbrust aus dem Joghurt nehmen, trockentupfen und in einem flachen Topf in etwas Pflanzenöl anbraten.
Die Gewürzpaste und Tomatenmark dazugeben und mit einkochen lassen.
. Mit den passierten Tomaten ablöschen und für ca. 10 Minuten bei mittlerer Hitze zu einer Sauce einkochen.
. Den Koriander grob hacken und kurz vor dem Anrichten zusammen mit dem Limettensaft und -abrieb unter das Tikka Masala mischen.