= Pikante Currywurst mit selbstgemachter Sauce

== Zutaten

* 1 scharfe rote Peperoni
* 2 Zwiebeln
* 1 Knoblauchzehe
* 3 EL Rapsöl
* 5 EL Tomatenmark
* 2 EL Weißweinessig
* 150 ml Cola
* 2 TL Currypulver
* 1 Messerspitze gemahlene Nelken
* 1 TL Paprikapulver
* 4 Bratwürste
* 100 g Apfelmus
* 4 Scheiben Brot
* Salz & Pfeffer

== Zubereitung

. 1 Peperoni waschen, entkernen und mit 2 Zwiebeln fein würfeln.
1 Knoblauchzehe hacken.
. 2 EL Öl in einem Topf erhitzen und Zwiebelwürfel mit Knoblauch und 5 EL Tomatenmark ca. 3-4 Minuten anbraten.
. Zwiebelwürfel mit 2 EL Essig, 150 ml Cola und 60 ml Wasser ablöschen.
Peperoniwürfel dazugeben, mit Salz, Pfeffer, 2 TL Currypulver, 1 Msp. Nelken und 1 TL Paprikapulver würzen und ca. 10 Minuten einkochen lassen.
. 1 EL Öl in einer Pfanne erhitzen und Bratwürste darin ca. 10 - 12 Minuten rumdherum braten.
. 100 g Apfelmus unter die Sauce rühren, aufkochen und pürieren.
Currysauce mit Salz und Pfeffer abschmecken.
. Bratwürste in Scheiben schneiden und mit Brot servieren.