= Falscher Schweinebraten

== Zutaten

* 10 mittelgroße festkochende Kartoffeln
* 2 große Zwiebeln
* 4 Kräuterseitlinge (Pilze)
* 2 EL Butter
* 2 Päckchen Räucherspeck in etwas dickeren Scheiben
* 1 Rosmarinzweig
* 250 ml Rotwein
* 60 ml Sake
* 30 ml Sojasoße
* Salz & Pfeffer

== Zubereitung

. Die Kartoffeln schälen und in Viertel schneiden, dann kochen, bis sie weich sind. 
(vll. in Milch statt Wasser kochen, dann werden sie cremiger)
. Das Wasser abgießen, anschließend die Kartoffeln grob stampfen und etwas abkühlen lassen.
. Den Ofen auf 120 Grad vorheizen.
. Die Zwiebeln schälen und würfeln, die Kräuterseitlinge waschen und ebenfalls würfeln.
Dann beides in 1 EL Butter goldbraun in einer Pfanne anbraten.
. Die Mischung zu der Kartoffelmasse hinzugeben, miteinander vermengen und mit Salz und Pfeffer nach Belieben würzen.
. Backpapier oder Frischhaltefolie auf der Arbeitsplatte auslegen, darauf dann eine Fläche mit Speck auslegen.
. Die Kartoffelmasse auf dem Speck verstreichen, dann die Speckscheiben aufrollen, indem man die Frischhaltefolie nach oben faltet und die Rolle mit Küchengarn oder Zahnstocher fixiert, so dass ein >>Braten<< entsteht.
Vorsicht, die Frischhaltefolie soll natürlich nicht mit fixiert werden!
. Die Rosmarinblätter vom Stiel zupfen und den >>Braten<< mit ihnen spicken, z.B. indem man sie unter das Küchengarn schiebt.