= Frühstücksbratlinge

== Zutaten

* 500 g Kartoffeln
* 3 Möhren
* 1 Zucchini
* 1 Zwiebel, fein gehackt
* 1 Ei
* 1/2 Bund Petersilie, fein gehackt
* 3 EL Paniermehl
* 1 TL frische Minze, fein gehackt
* Salz, Pfeffer, Pflanzenöl

== Zubereitung

. Die Kartoffeln und die Möhren schälen, waschen und gut abtropfen lassen. 
In grobe Stücke schneiden.
. Die Zucchini waschen, die Enden kappen und in grobe Stücke schneiden. 
Zusammen mit den Kartoffeln und den Möhren fein raspeln. 
In einem Sieb abtropfen lassen. 
. Die Gemüseraspeln in eine Schüssel geben.
Das Ei, die Petersilie, das Paniermehl und die Minze hinzufügen, kräftig mit Salz und Pfeffer würzen und alles gut vermengen. 
Aus der Gemüsemasse ca. 3 cm dicke Bratlinge formen. 
. Jeweils 3 EL Pflanzenöl in eine beschichtete Pfanne geben und bei mittlerer Hitze erwärmen.
Je nach Pfannengröße einige Bratlinge hineingeben und von beiden Seiten goldgelb ausbacken (ca. 5 Minuten).
Zum Abtropfen auf einen mit Küchenpapier ausgelegten Teller geben.
. Zusammen mit einem Dip servieren.