= Kalte Tomatensuppe mit Hackbällchen-Sticks

== Zutaten

Für die Suppe:

* 1 EL Korianderkörner
* 1 EL Langpfeffer oder Stielpfeffer (ersatzweise schwarze Pfefferkörner)
* 1 EL Zucker
* 100 ml frisch gepresster Orangensaft
* 100 ml Olivenöl
* 1 kg Tomaten
* 1 El Currypulver oder Garam Masala
* 1 Bund Koriander

Für die Hackbällchen:

* 1 Bio-Zitrone
* 250 g Schweinehackfleisch
* 2 EL Olivenöl
* 4 EL Sojasauce
* 8 kleine Holzspieße
* Salz & Pfeffer

== Zubereitung

. Für die Suppe Korianderkörner und Pfeffer in einem Mörser oder einem elektrischen Blitzhacker grob mahlen. 
In einem kleinen Topf den Zucker mit 1 EL Wasser erhitzen, bis der Zucker goldbraun karamellisiert ist.
Pfeffer dazugeben und unter Rühren 30 Sekuznden karamellisieren.
Mit dem Orangensaft ablöschen und bei starker Hitze auf 2 EL einkochen.
Topf vom Herd nehmen, die Mischung mit dem Öl verrühren, 10 Minuten ziehen lassen.
. Die Tomaten waschen und grob zerkleinern, dabei die Stielansätze entfernen.
Tomaten mit Currypulver oder Garam Masala in eine hohe Rührschüssel geben und mit einem Stabmixer fein pürieren, dann durch ein Sieb streichen.
Das Pfefferöl ebenfalls durch ein Sieb gießen und unter das Tomatenpüree rühren.
Mit Salz abschmecken.
Suppe bis zum Servieren kalt stellen.
Koriandergrün abbrausen und trockenschütteln, die Blättchen abzupfen und grob hacken.
. Für die Hackbällchen die Zitrone heiß waschen und abtrocknen, die Schale fein abreiben.
Hackfleisch mit Zitronenschale, wenig Salz und reichlich Pfeffer würzen und kurz durchmengen.
Mit feuchten Händen 12 kleine Bällchen aus der Masse formen.
. In einer beschichteten Pfanne das Öl erhitzen.
Darin die Hackbällchen bei mittlerer Hitze 5-6 Minhuten knusprig braun braten.
Zum Schluss die Bällchen ab und zu mit etwas Sojasauce bepinseln.
Je 2 Bällchen auf einen Holzspieß stecken.
Die Suppe in Tassen verteilen und mit Koriandergrün bestreuen, Spießchen dazulegen.