= Nougat Panna Cotta mit Erdbeer-Minz-Ragout

== Zutaten

Für die Panna Cotta:

* 3 Blätter Gelatine
* 400 ml Sahne
* 2 Stangen Nougat Noir
* 2 Stangen Nougat Royal
* 1 Prise Salz

Für das Erdbeer-Minz-Ragout:

* 200 g Erdbeeren
* 15 ml Läuterzucker
* 4 Minzblätter
* etwas Zitronenabrieb

== Zubereitung

. Die Gelatine in kaltem Wasser einweichen.
. Die Sahne in einem Topf aufkochen, die eingeweichte Gelatine ausdrücken und in der Sahne auflösen.
. Jeweils eine Schüssel mit grob geschnittenem Nougat Noir und Nougat Royal vorbereiten.
. Die Hälfte der Sahne über den Nougat Noir, die andere Hälfte über den Nougat Royal geben und beides zu einer glatten Masse verrühren.
Mit einer Prise Salz verfeinern.
. Die Nougat Royal-Masse in die Gläser füllen und für ca. 1 Stunde kühl stellen.
. Danach die zweite, dunkle Masse dazu geben und für eine weitere Stunde kalt stellen.
. In der Zwischenzeit die Erdbeeren waschen, trocken tupfen und in gleichmäßige Stücke schneiden.
. Die Erdbeerstücken in eine Schüssel geben, mit Zitronenabrieb und Läuterzucker verfeinern.
Mit fein geschnittener Minze veredeln.
. Sobald die Panna Cotta fest ist, das Erdbeer-Minz-Ragout darüber geben und servieren.