= Nougat-Masala Chai indischer Gewürztee

== Zutaten

* 2 Nelken
* 1 Kapsel Grüner Kardamom
* 1 TL ganzer schwarzer Pfeffer
* 3 Piment oder Nelkenpfeffer
* 100 g Ingwer
* 2 Stangen Zimt
* 5 g Assam tee
* 600 ml Milch
* 1 Stange Nougat Royal
* 1 Prise Zimt
* 1 Prise Salz

== Zubereitung

. Nelken, Kardamomkerne, Pfeffer und Piment in einen Mörser geben und die Gewürze zerstoßen.
. Den Ingwer schälen und in feine Streifen schneiden.
Davon ein wenig zur Dekoration beiseite legen.
Alle Gewürze in 0.5 l Wasser bis zum Siedepunkt bringen und 20 Minuten ziehen lassen, aber nicht kochen.
. Den Assam tee dazu geben und nochmals 3-5 Minuten ziehen lassen.
. Alle Gewürze abseihen.
Den Gewürztee mit einer Prise Salz verfeinern und in die Gläser füllen.
. Die Milch erhitzen, den Nougat darin komplett schmelzen und mit einem Schneebesen oder Milchaufschäumer aufschäumen, anschließend auf die Gläser verteilen.
. Geraspelten Ingwer und eine Prise Zimt als Topping auf den Michschaum geben und servieren.