= Ofentomaten mit Honigkäse

== Zutaten

* 500 g Cocktailtomaten
* 8 Zweige Thymian
* 4 Stängel Basilikum
* 6 EL Olivenöl
* 4 Ziegenfrischkäsetaler
* 1/2 EL Honig
* 1 EL schwarze Oliven
* 1 EL milder Essig
* Salz & Pfeffer

== Zubereitung

. Den Backofen auf 200 °C vorheizen. 
Die Tomaten waschen, halbieren und mit den Schnittflächen nach oben in eine ofenfeste Form legen. 
Den Thymian waschen und trocken schütteln.
Die Blättchen von den Stielen streichen und mit Salz und Pfeffer über die Tomaten streuen.
Die Tomaten mit 4 EL Olivenöl beträufeln und im heißen Ofen (Mitte) ca. 20 Minuten backen, bis sie leicht gebräunt sind.
Dann herausnehmen.
. Die Backofentemperatur auf 250 °C erhöhen.
Die Käsetaler nebeneinander in eine ofenfeste Form legen.
Den Honig mit 1 EL Olivenäl gut verrühren. 
(Bei Bedarf leicht erwärmen, damit der Honig sich auflöst.)
Honigöl auf die Käsetaler streichen und diese im Backofen 3-4 Minuten backen oder grillen, bis der Käse leicht gebräunt ist.
. Inzwischen das Basilikum waschen, trocken schütteln und die Blättchen von den Stielen zupfen.
Das Basilikum und die Oliven unter die gebackenen Tomaten mischen.
Den Essig mit 1 EL Öl cremig schlagen und ebenfalls unterheben.
Die Ofentomaten mit Salz und Pfeffer abschmecken und mit den Käsetalern auf vier Tellern anrichten.
Sofort servieren.
