= Pasta mit gebackenem Feta

== Zutaten

* 300 g Kirschtomaten
* 8 Stiele Thymian
* 2 Knoblauchzehen
* 1 rote Zwiebel
* 1/2 Zitrone
* 200 g Feta
* 4 EL Olivenöl
* 300 g Spaghetti
* Salz & Pfeffer

== Zubereitung

. Tomaten waschen und gut abtropfen lassen, Thymian waschen, trocken schütteln und vom Stiel zupfen.
Knoblauch schälen und fein hacken.
Zwiebel schälen, halbieren und in feine Streifen schneiden.
Zitrone auspressen.
. Feta abtropfen lassen und mittig in eine Auflaufform (ca. 20 x 15 cm) setzen.
Tomaten, Knoblauch, Zwiebeln und Thymian um den Feta verteilen.
. Feta und Gemüse mit Olivenöl und Zitronensaft beträufeln, mit Salz und Pfeffer würzen und 20-25 Minuten bei 220 °C (Ober-/Unterhitze) im Ofen auf der mittleren Schiene backen.
. Währenddessen Spaghetti nach Packungsanweisung kochen und abgießen.
Kräuter waschen, trocken schütteln und grob hacken.
. Auflaufform aus dem Ofen nehmen, Feta und Tomaten mit einer Gabel grob zerkleinern.
Spaghetti aus dem Nudelsieb in die Auflaufform füllen und mit Käse und Gemüse gründlich vermengen.
Servieren und Genießen.