= Pietsmiet Burger

== Zutaten

Für die Burger-Brötchen:

* 250 g Mehl
* 2 Eier
* 115 ml Wasser
* 25 g weiche Butter
* 20 g Milchpulver
* 20 g Zucker
* 5 g Salz
* 1/2 Päckchen Trockenhefe
* etwas Sesam

Für den Belag:

* 1 Eisbergsalat
* 1 rote Zwiebel
* 12 Scheiben Bacon
* 8 Rindfleisch-Burger-Patties
* 4 Scheiben Cheddarkäse
* Salsasoße & Ketchup
* Öl zum anbraten

== Zubereitung

. Das Mehl, 1 Ei, das Wasser, die Butter, das Milchpulver, den Zucker, das Salz und die Trockenhefe erst auf niedriger, dann auf höherer Stufe verkneten, bis ein glatter Teig entsteht.
Anschließend den Teig für ca. 1 Stunde gehen lassen.
. Den Teig in vier gleich große Stücke teilen und zu Kugeln formen.
Dann die Teiglinge auf einem Backblech etwas flach drücken und nochmal 30 Minuten gehen lassen.
. Das übrig gebliebene Ei trennen und die Teiglinge mit dem verquirlten Eigelb bestreichen, dann nach Belieben Sesam darüberstreuen.
. Für ca. 15 Minuten bei 180 Grad in den Ofen schieben.
. Währenddessen den Eisbergsalat vom Strunk lösen und waschen sowie die rote Zwiebel schälen und in Ringe schneiden.
. Den Bacon und die Rindfleischpatties in etwas Öl anbraten.
. Die Brötchen aufschneiden und für den Original PietSmiet Burger, den es auch mal bei McDonald's gab (danke, Marc Emde!), in folgender Reihenfolge belegen (von unten nach oben): zwei Lagen Bacon (am besten je zwei nebeneinander und über Kreuz), erstes Patty, eine Scheibe Cheddarkäse, zweites Patty, Eisbergsalat, rote Zwiebelringe, Ketchup, Salsasoße.