= Spinatklösschen mit Tomatensalat

== Zutaten

Für die Klößchen:

* 100 g junger Blattspinat
* 150 g Magerquark
* 2 Scheiben Toastbrot
* 1 kleine Knoblauchzehe
* 1 EL weiche Butter
* 1 Messerspitze abgeriebene Bio-Zitronenschale
* 100 g Ziegenfrischkäse
* Salz & Pfeffer

Für den Tomatensalat:

* 500 g Tomaten
* 2 Schalotten
* 1/2 Bund Petersilie
* 2 EL Weißweinessig
* 1/2 TL Zucker
* 5 EL Olivenöl
* Salz & Pfeffer

== Zubereitung

. Spinat wachen, abtropfen lassen und verlesen, grobe Stiele abschneiden.
Wasser in einem Topf aufkochen und salzen.
Spinat ins kochende Salzwasser geben, nach ca. 15 Sekunden in ein Sieb abgießen, eiskalt abschrecken und abtropfen lassen.
Mit einem Löffel ausdrücken und hacken.
. Quark in einem Küchentuch ausdrücken.
Toast entrinden und zu Bröseln hacken.
Knoblauch schälen und fein würfeln.
Butter mit Zitronenschale, Salz und Pfeffer mit den Schneebesen des Handrührgeräts cremig rühren.
Quark, Ziegenkäse, Spinat, Knoblauch und die Toastbrösel dazugeben.
Alles zu einer glatten Masse verrühren, salzen und pfeffern.
Mit angefeuchteten Händen kleine Kugeln aus der Masse formen.
Die Kugeln zugedeckt ca. 30 Minuten kalt stellen.
. Inzwischen für den Salat die Toamten waschen, vom Stielansatz befreien, halbieren und würfeln.
Schalotten schälen und fein würfeln.
Petersilie waschen und trocken schütteln, Blätter abzupfen und bis auf einen kleinen Rest fein hacken.
Essig, Salz, Pfeffer und Zucker mit einem Schneebesen verquirlen.
Das Olivenöl unterschlagen, bis eine cremige Sauce entstanden ist.
Tomaten, Schalotten und Petersilie untermischen.
. Den Tomatensalat mit den Spinatbällchen anrichten und die übrige Petersilie obendrauf streuen.
Dazu passt frisches Baguette oder Fladenbrot.