= Zuccini-Lasagne

== Zutaten

* 4 EL Mandelmus
* 100 ml Wasser
* 4 Zucchini
* 2 Gemüsezwiebeln
* 4 Knoblauchzehen
* 500 g Rinderhackfleisch
* 2 EL Tomatenmark
* 2 Dosen Tomaten (stückig)
* 2 EL Curry
* 2 EL Oregano (getrocknet)
* 2 EL Paprikapulver (scharf)
* 2 EL Chiliflocken
* 2 EL Basilikum (getrocknet)
* 8 EL Käse (gerieben, fettarm)
* Salz & Pfeffer

== Zubereitung

. Den Ofen auf 200 Grad vorheizen.
. Das Mandelmus mit dem Wasser in eine Schüssel geben und mit einer Prise Salz und Pfeffer würzen.
Gut umrühren.
. Die Zucchini waschen und die Enden abschneiden.
Danach in dünne Scheiben schneiden und mit etwas Salz bestreuen.
. Die Zwiebeln und den Knoblauch schälen und klein schneiden.
Beides in einer Pfanne anbraten, bis sie glasig werden.
Dazu brauchst du kein Öl.
Es eigenen sich genauso Wasser oder Brühe.
. Nun das Hackfleisch hinzufügen und bei mittlerer hitze mitbraten, bis es vollkommen durchgebraten ist.
Dabei immer gut umrühren.
. Das Tomatenmark, die Tomaten und die Gewürze zum Fleisch geben und alles gut miteinander vermischen.
Mit Salz und Pfeffer abschmecken, danach die Pfanne von der Herdplatte nehmen.
. Den Boden einer Auflaufform mit Zucchinischeiben auslegen.
Darauf dann eine Schicht der Hack-Tomaten-Soße geben.
Die dritte Schicht bildet die Mandelmus-Mischung.
Gib 4-6 EL über die Lasagne.
Nun folgt wieder eine Schicht aus Zucchini und darauf noch einmal eine Schicht mit Hack-Tomaten-Soße usw.
Bestreue die Lasagne abschließend mit dem Käse.
Falls noch etwas von der Mandelmus-Mischung übrig ist, verteile sie über die Lasagne.
. Die Lasagne ca. 20 Minuten backen, bis sie eine goldbraune Farbe hat.